<?php print form_text_field($foodinfo, 'FoodId'); ?>
<?php print form_text_field($foodinfo, 'DanName'); ?>
<?php print form_text_field($foodinfo, 'ProdName'); ?>
<?php print form_text_field($foodinfo, 'EngName'); ?>
<?php print form_text_field($foodinfo, 'SysName'); ?>
<?php print form_text_field($foodinfo, 'MainGrp'); ?>
<?php print form_text_field($foodinfo, 'SubGrp'); ?>
<?php print form_text_field($foodinfo, 'Waste'); ?>
<?php print form_text_field($foodinfo, 'NCF'); ?>
<?php print form_text_field($foodinfo, 'FACF'); ?>
<?php print form_text_field($foodinfo, 'PEF'); ?>
<?php print form_text_field($foodinfo, 'FEF'); ?>
<?php print form_text_field($foodinfo, 'CEF'); ?>
<?php print form_text_field($foodinfo, 'Density'); ?>
<?php print form_text_field($foodinfo, 'Remarks'); ?>
<?php print form_text_field($foodinfo, 'PublStatus'); ?>
<?php print form_text_field($foodinfo, 'LanguaL'); ?>
<?php print form_text_field($foodinfo, 'GRIN'); ?>
<?php print form_text_field($foodinfo, 'FISHBASE'); ?>
<?php print form_text_field($foodinfo, 'BASIS'); ?>
<?php print form_text_field($foodinfo, 'USDA'); ?>
<?php print form_text_field($foodinfo, 'FIFood'); ?>
<?php print form_text_field($foodinfo, 'UKFood'); ?>
<?php print form_text_field($foodinfo, 'FRFood'); ?>
<?php print form_text_field($foodinfo, 'DEFood'); ?>
<?php print form_text_field($foodinfo, 'SEFood'); ?>
<?php print form_text_field($foodinfo, 'NOFood'); ?>
<?php print form_text_field($foodinfo, 'NLFood'); ?>
<?php print form_text_field($foodinfo, 'ISFood'); ?>
<?php print form_text_field($foodinfo, 'SPFood'); ?>
<?php print form_text_field($foodinfo, 'ITFood'); ?>
<?php print form_text_field($foodinfo, 'DateUpdated'); ?>
<?php print form_text_field($foodinfo, 'UpdatedBy'); ?>
<?php print form_text_field($foodinfo, 'Recipe'); ?>
<?php print form_text_field($foodinfo, 'WaterYield'); ?>
<?php print form_text_field($foodinfo, 'FatYield'); ?>
<?php print krudt_form_footer(); ?>
