<?php print form_text_field($nutrient, 'RefId'); ?>
<?php print form_text_field($nutrient, 'PubTypeId'); ?>
<?php print form_text_field($nutrient, 'AcqTypeId'); ?>
<?php print form_text_field($nutrient, 'Title'); ?>
<?php print form_text_field($nutrient, 'Authors'); ?>
<?php print form_text_field($nutrient, 'Publishr'); ?>
<?php print form_text_field($nutrient, 'PubDate'); ?>
<?php print form_text_field($nutrient, 'Version'); ?>
<?php print form_text_field($nutrient, 'OrigLang'); ?>
<?php print form_text_field($nutrient, 'Languages'); ?>
<?php print form_text_field($nutrient, 'ISBN'); ?>
<?php print form_text_field($nutrient, 'FstEdDat'); ?>
<?php print form_text_field($nutrient, 'EdNo'); ?>
<?php print form_text_field($nutrient, 'NoPages'); ?>
<?php print form_text_field($nutrient, 'BkTitle'); ?>
<?php print form_text_field($nutrient, 'Editors'); ?>
<?php print form_text_field($nutrient, 'Pages'); ?>
<?php print form_text_field($nutrient, 'LgJrName'); ?>
<?php print form_text_field($nutrient, 'AbJrName'); ?>
<?php print form_text_field($nutrient, 'ISSN'); ?>
<?php print form_text_field($nutrient, 'Volume'); ?>
<?php print form_text_field($nutrient, 'Issue'); ?>
<?php print form_text_field($nutrient, 'SeriName'); ?>
<?php print form_text_field($nutrient, 'SeriNo'); ?>
<?php print form_text_field($nutrient, 'RprtTitle'); ?>
<?php print form_text_field($nutrient, 'FileFrmt'); ?>
<?php print form_text_field($nutrient, 'WWW'); ?>
<?php print form_text_field($nutrient, 'Medium'); ?>
<?php print form_text_field($nutrient, 'OS'); ?>
<?php print form_text_field($nutrient, 'Media'); ?>
<?php print form_text_field($nutrient, 'Valid'); ?>
<?php print form_text_field($nutrient, 'Remarks'); ?>
<?php print form_text_field($nutrient, 'FoodId'); ?>
<?php print form_text_field($nutrient, 'DateUpdated'); ?>
<?php print form_text_field($nutrient, 'UpdatedBy'); ?>
<?php print form_text_field($nutrient, 'DocLink'); ?>
<?php print krudt_form_footer(); ?>
